esphome:
  name: device

rp2040:
  board: rpipicow
  framework:
    # Required until https://github.com/platformio/platform-raspberrypi/pull/36 is merged
    platform_version: https://github.com/maxgerhardt/platform-raspberrypi.git

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "key"

ota:
  password: "password"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "fallback"
    password: "password"
  domain: ".local.lan"

i2c:
  sda: GPIO20 
  scl: GPIO21 
  scan: true
  id: bus_a 


sensor:
  - platform: bme280
    temperature:
      name: "Temperature"
      oversampling: 1x
      id: bme_temp
    humidity:
      name: "Humidity"
      oversampling: 1x
      id: bme_hum
    pressure:
      name: "Pressure"
      oversampling: 1x
      id: bme_pres
    address: 0x77
    update_interval: 60s